http:
  middlewares:
    redirect-non-www-to-www:
      redirectregex:
        regex: "^https?://(?:www\\.)?(.+)"
        replacement: "https://www.${1}"

    redirect-www-to-non-www:
      redirectregex:
        regex: "^https?://www\\.(.+)"
        replacement: "https://${1}"
