http:
  middlewares:
    compression:
      compress:
        includedContentTypes: text/plain, text/css, text/html, text/xml, text/javascript, application/json, application/xml, application/xml+rss, image/svg+xml

    redirect-non-www-to-www:
      redirectregex:
        regex: "^https?://(?:www\\.)?(.+)"
        replacement: "https://www.${1}"

    redirect-www-to-non-www:
      redirectregex:
        regex: "^https?://www\\.(.+)"
        replacement: "https://${1}"
